maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformBomMojo.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomConfig.java, pom.xml
When the original platform BOM is read, `${project.version}` property which may appear as a value in some dependencies (which is not currently the case but will probably be in the future) will not be replaced. This PR fixes that.
The dependency on Quarkus core is upgraded to 1.9.0.Final.
=> Support for project.version property reading the original BOM

bom-decomposer/src/main/java/io/quarkus/bom/decomposer/PomUtils.java, maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformBomMojo.java, platform-bom/pom.xml, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomUtils.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformCatalogResolver.java, pom.xml
Currently platform descriptors are ordered along with the rest of the managed dependencies alphabetically, which isn't right, given that those that appear earlier in the list are overriding metadata contained in those appearing later.
=> Properly order platform descriptors in the generated platform BOM

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Currently, unless configured explicitly, the platform release version is set to micro version of the current project.
=> Use full version as the platform version instead of simply the micro version

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
For some reason, using a property breaks the release plugin.
=> Use the actual version of the universal BOM in imports instead of property

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java, maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/util/Utils.java, platform-bom/src/main/java/io/quarkus/bom/platform/ExtensionCoordsFilterFactory.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
Currently members that don't provide a BOM are not participating in extension filtering, which results in issues like https://github.com/quarkusio/quarkus-platform/pull/277#discussion_r677611504
This PR fixes it.
=> Derive the primary member groupId from its extension artifacts unless the member provided a BOM

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Use testCatalogArtifact version rather than originalBomCoords for testArtifacts from testCatalogArtifact itself.
=> #72 use version from testCatalogArtifact in GeneratePlatformProjectMojo

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/BuildPlatformProjectMojo.java
This would be handy in a situation when there are known issues in some of the generated test projects.
=> Add property for skipping invoke-platform-project mojo

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Fixes #81
With this change we are going to check whether the module name already exists in the parent POM before using for the test module and if it does warn and use `testArtifact.getArtifactId() + "-" + testArtifact.getVersion()` instead. If that module name also exists, throw an error.
=> Check whether the parent already includes the module name for the test module

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java, maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberConfig.java
Defaulting to the member BOM groupId.
=> Limit member descriptor generator to specific member extension artifactIds

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformMemberDefaultTestConfig.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformMemberTestConfig.java
This option allows to configure the `io.quarkus:quarkus-maven-plugin` with the `build` goal for test modules that would package the app before running `QuarkusIntegrationTest`s.
=> packageApplication option for tests

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformMember.java, platform-bom/src/main/java/io/quarkus/bom/platform/PlatformMemberConfig.java
If a member configures "own" groupIds, constraints with these groupIds can't be overridden by other members.
=> Support for configuring member own groupIds

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
To make sure the platform BOM is enforced on the transitive dependencies of the plugin.
=> Keep dependencyManagement when flattening the Maven plugin's pom

platform-bom/src/main/java/io/quarkus/bom/platform/DependencyManagementConfig.java, platform-bom/src/main/java/io/quarkus/bom/platform/DependencySpec.java
@aloubyansky I'd need this to be able to force using the newest Mandrel in the Platform without rebuilding Quarkus core. 
Something like 
```
<dependencySpec>
<artifact>org.graalvm.nativeimage:svm:${graalvm.version}</artifact>
<scope>provided</scope>
<exclusions>
<exclusion>*:*</exclusion>
</exclusions>
</dependencySpec>
```
See around here: https://gitlab.cee.redhat.com/ppalaga/quarkus-platform/-/commit/c38288bcf292fd31773fb57dcc13fe103a5179c4?page=14#442292b8a7efeabbe4cc176709b833b1792140ec_69_73
I'd need a release if this change looks good.
=> Allow DependencySpecs with a custom scope

domino/api/src/main/java/io/quarkus/domino/ProjectDependencyConfig.java, domino/api/src/main/java/io/quarkus/domino/ProjectDependencyConfigImpl.java, domino/api/src/main/java/io/quarkus/domino/ProjectDependencyResolver.java, domino/app/src/main/java/io/quarkus/domino/cli/BaseDepsToBuildCommand.java
This change introduces a config option to allow passing a local project dir, e.g.
```
java -jar target/domino.jar from-maven report --project-dir=<path-to-project>
```
FYI @goldmann, this is the Maven part of https://github.com/quarkusio/quarkus-platform-bom-generator/issues/171
Ideally we'll want a single command that will work for both Maven and Gradle. I just wanted to add this feature, ASAP, in case it helps.
=> Domino: support for analyzing dependencies of a local Maven project by providing the project dir

domino/app/src/main/java/io/quarkus/domino/cli/BaseDepsToBuildCommand.java
In order to be able to provide a comma-separated artifacts list to the --root-artifacts flag (e.g. --root-artifacts=a1,a2,a3), I added split="," to the annotation associated with said flag.
Changed from what we currently have (6.1.1 from doc below), to use a comma split (6.2 from doc below)
https://picocli.info/#_multiple_values
=> Domino: Added comma-separated multi input functionality to --root-artifacts command line flag

domino/api/src/main/java/io/quarkus/domino/manifest/PurgingDependencyTreeVisitor.java, domino/api/src/main/java/io/quarkus/domino/manifest/SbomGeneratingDependencyVisitor.java, domino/api/src/main/java/io/quarkus/domino/manifest/SbomGenerator.java, domino/api/src/test/java/io/quarkus/domino/manifest/ProjectManifestingTest.java, domino/api/src/test/resources/projects/simple-pom/pom.xml, domino/api/src/test/resources/projects/single-jar-and-bom/bom/pom.xml, domino/api/src/test/resources/projects/single-jar-and-bom/library/pom.xml, domino/api/src/test/resources/projects/single-jar-and-bom/pom.xml
FYI @vibe13 
If product info isn't configured, it will now try picking one of the components that are top level (roots of the dependency trees) as the main component for a generated SBOM using the following strategy:
1. if there is only one top level component in an SBOM it will be picked as the main one;
2. if a project BOM was configured, the BOM artifact will be preferred as the main component;
3. if there is only one non-`pom` top level component (typically a jar) it will be picked as the main one;
4. if there was a `projectDir` configured, it will use the module the `projectDir` points to as the main component.
=> Add default main SBOM component in case product info is not configured

domino/README.md, domino/app/src/main/java/io/quarkus/domino/cli/Quarkus.java
A list of non Red Hat version artifacts for redhat-version-rate option
Introduces `--log-not-matched` option that can be used in the future in combination with other options than just `--redhat-version-rate`.
Example command: `domino quarkus --version 3.8.5.SP1-redhat-00001 --members=quarkus-bom --redhat-version-rate --extension-versions='*redhat*' --log-not-matched`
=> A list of non Red Hat version artifacts for redhat-version-rate option

domino/api/src/main/java/io/quarkus/domino/manifest/ManifestGenerator.java, domino/api/src/main/java/io/quarkus/domino/manifest/SbomGenerator.java, domino/app/src/main/java/io/quarkus/domino/cli/Report.java, maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/DependenciesToBuildMojo.java, pom.xml
Upgrade to Quarkus 3.15.2 and CycloneDX 1.6 schema by default.
=> Upgrade to Quarkus 3.15.2

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
This fixes an issue when we enable repositories in a profile in the platform project.
=> Re-use remote repos injected in the mojo when creating a collect request during the platform project generation

maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformDescriptorJsonMojo.java, maven-plugin/src/main/java/io/quarkus/maven/ValidateExtensionsJsonMojo.java, pom.xml
In Quarkus, I modified the JSON mapper to be more reproducible, we had issues with the order of properties not being stable in the generated JSON file.
This will require an update of the Quarkus version used, which I think shouldn't be an issue.
There's one issue though: a constant has been dropped but AFAICS, we changed to a YAML file in 0.27.0 so a veeeerrrryyyy long time ago.
Note: this will be a bit disruptive as the generated Platform will probably contain a lot of changes compared to what was generated. But it should be a lot more stable after that.
=> Prepare upgrade to recent Quarkus version as part of reproducible builds
