quarkusio/quarkus-platform-bom-generator

- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
If a POM artifact does not actually exists, the artifact descriptor will still be returned apparently.
> Make sure the POM file actually exists in the local repo before returning the ArtifactDescriptorResult

- .github/workflows/build.yml
(test from GH UI to see if it sets up a build)
> Add a CI workflow

- bom-decomposer/src/main/java/io/quarkus/bom/decomposer/PomUtils.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/FlattenPlatformBomMojo.java
- pom.xml
Goal for flattening the platform BOM.
> flatten-platform-bom goal

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/FlattenPlatformBomMojo.java
Use the proper `type` for managed dependencies and duplicate 'test-jar' dependencies: one time with classifier 'tests' (the default) and one time w/o the classifier.
> flatten-platform-bom: get the dependency type from Artifact.getProperties().get('type')

- bom-decomposer/src/main/java/io/quarkus/bom/decomposer/BomDecomposer.java
- bom-decomposer/src/main/java/io/quarkus/bom/diff/HtmlBomDiffReportGenerator.java
- maven-plugin/pom.xml
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformBomMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformDescriptorJsonMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/BuildPlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/DelegatingExecutionListener.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformBomGeneratorConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformBomLifecycleParticipant.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformDescriptorGeneratorConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberReleaseConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformStackConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/Element.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/ElementCatalog.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/ElementCatalogBuilder.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/Member.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/Playground.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/Union.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/playground/UnionVersion.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomMemberConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/ReportIndexPageGenerator.java
- pom.xml
Prototype alternative platform project configuration
> Prototype alternative platform project configuration

- bom-decomposer/src/main/java/io/quarkus/bom/decomposer/BomDecomposer.java
- bom-decomposer/src/main/java/io/quarkus/bom/decomposer/UpdateAvailabilityTransformer.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformBomMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformBomGeneratorConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/ExtensionCoordsFilter.java
- platform-bom/src/main/java/io/quarkus/bom/platform/ExtensionCoordsFilterFactory.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomMemberConfig.java
Make sure member BOMs do not list extensions of other members and non-member Quarkiverse extensions
> Extension coords filtering

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomMemberConfig.java
Members w/o a BOM can specify their constraints in the new dependencyManagement config element
> Support for members without a BOM in the new platform project model

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformDescriptorJsonMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformReleaseConfig.java
Refactored `platformStack` config into `platformRelease`, changed the property `platform.stack.stream` to `platform.release-info@...`, added the platform key to the property value.
> Refactored platformStack config into platformRelease

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberDefaultTestConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberReleaseConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberTestConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
Renamed upcoming config element to next
Support for configuring extra test dependencies
Remove the generated platform project when clean is found among the goals
> A few platform gen config enhancements

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformDescriptorJsonMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformReleaseConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformReleaseWithMembersConfig.java
This PR eliminates the need to explicitly provide the platform release config.
> Support for the platform release config defaults

- maven-plugin/pom.xml
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- pom.xml
This allows to have a consistent ordering of properties and suppress the date comment.
> Use OrderedProperties for storing the properties artifacts

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
> Do not generate test dependencies on POMs with *:* exclusions

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
> Use version properties for the test artifacts in the generated POMs where possible

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
> Generate disabled test modules with maven.test.skip=true property

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/UniversalPlatformConfig.java
> Added 'universal' element to group the universal platform config

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformBomMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
- platform-bom/src/main/java/io/quarkus/bom/platform/ReportIndexPageGenerator.java
The universal descriptor is currently missing the metadata from core.
> Make sure the universal descriptor has a copy of the metadata from core

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberReleaseConfig.java
Record detected member BOM updates in the JSON files.
> Record last BOM update for each member

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/util/Utils.java
Initialize Maven POM Models with sorted Properties implementation.
> Sorted Model properties

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Generates release info config for the universe json descriptor.
> Add release info to the universe json descriptor

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformDescriptorJsonMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberConfig.java
> Support for configuring member-specific metadata override local files and Maven artifacts

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberDefaultTestConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformMemberTestConfig.java
Support for configuring test excludes and includes in a test plugin configuration.
> Support for test plugin excludes/includes

- .github/workflows/build.yml
Just like https://github.com/quarkusio/quarkus/pull/19414
> Switch to Eclipse Temurin JDK via actions/setup-java

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
> Make sure plugin-help.xml is loadable for quarkus:help

- platform-bom/src/main/java/io/quarkus/bom/platform/ExtensionCoordsFilterFactory.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
> Don't filter other member constraints from the original member BOM

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/AttachedMavenPluginConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Introduces an option to import the original Maven plugin sources and re-build the platform Maven plugin from those and the platform G:A:V.
> An option to build the Maven plugin from sources

- bom-decomposer/src/main/java/io/quarkus/bom/decomposer/BomDecomposer.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/FlattenPlatformBomMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Also exclude non-existing constraints from the platform BOM
> filterInvalidConstraints option for the flatten-platform-bom

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/DependenciesToBuildMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/NonProductizedDepsMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformBomComposer.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformMember.java
- platform-bom/src/main/java/io/quarkus/bom/platform/PlatformMemberConfig.java
- pom.xml
Also
* upgrade to Quarkus 2.10.0.Final
* option to allow members to configure their own exclusions for common dependencies
* Maven goal to report dependencies of supported Quarkus extensions that haven't been built from source
> Maven goal to calculate dependencies above and bellow a certain dependencies

- bom-decomposer/src/main/java/io/quarkus/bom/decomposer/ReleaseIdResolver.java
- domino/api/src/main/java/io/quarkus/domino/CircularReleaseDependenciesException.java
- domino/api/src/main/java/io/quarkus/domino/CircularReleaseDependency.java
- domino/api/src/main/java/io/quarkus/domino/DependencyTreeVisitor.java
- domino/api/src/main/java/io/quarkus/domino/PncBuildInfoProvider.java
- domino/api/src/main/java/io/quarkus/domino/PncReleaseIdDetector.java
- domino/api/src/main/java/io/quarkus/domino/ProjectDependencyResolver.java
- domino/api/src/main/java/io/quarkus/domino/ResolvedDependency.java
- domino/api/src/main/java/io/quarkus/domino/manifest/PncArtifactBuildInfo.java
* introduce CircularReleaseDependenciesException
* add ReleaseId to DependencyVisit
* add local PNC info cache
> Circular release deps exception

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/ExtensionChangesMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/GeneratePlatformDescriptorJsonMojo.java
Mojo identifying extension status changes compared to previous platform release in a given stream (removed, new, version update, classpath update)
> Mojo identifying extension status changes compared to previous platform release

- domino/api/src/main/java/io/quarkus/domino/DependencyTreeVisitor.java
- domino/api/src/main/java/io/quarkus/domino/LoggingDependencyTreeVisitor.java
- domino/api/src/main/java/io/quarkus/domino/ProjectDependencyConfig.java
- domino/api/src/main/java/io/quarkus/domino/ProjectDependencyConfigImpl.java
- domino/api/src/main/java/io/quarkus/domino/ProjectDependencyResolver.java
- domino/api/src/main/java/io/quarkus/domino/manifest/ManifestGenerator.java
- domino/api/src/main/java/io/quarkus/domino/manifest/Playground.java
- domino/api/src/main/java/io/quarkus/domino/manifest/PurgingDependencyTreeVisitor.java
- domino/api/src/main/java/io/quarkus/domino/manifest/SbomGeneratingDependencyVisitor.java
- domino/api/src/main/java/io/quarkus/domino/manifest/SbomGenerator.java
- domino/api/src/main/java/io/quarkus/domino/processor/NodeTask.java
- domino/app/src/main/java/io/quarkus/domino/cli/Report.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/DependenciesToBuildMojo.java
> Added an option to record all direct dependencies of each component when generating a manifest

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Fixes https://github.com/quarkusio/quarkus-platform-bom-generator/issues/310
> Copy release profile activation and plugin management to generated BOM POMs

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
Since the generated BOMs don't have parent POMs.
> Use specific versions for the release plugins in the generated BOMs

- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/GeneratePlatformProjectMojo.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/PlatformConfig.java
- maven-plugin/src/main/java/io/quarkus/bom/decomposer/maven/platformgen/SbomerGlobalConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/SbomConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/SbomerConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/SbomerErrataConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/SbomerGeneratorConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/SbomerProcessorConfig.java
- platform-bom/src/main/java/io/quarkus/bom/platform/SbomerProductConfig.java
Enables generation of `.sbomer/config.yaml` based on member sbom configs and whether they are included in a release or not.
> Enable SBOMer config generation from the platform config

- domino/api/src/main/java/io/quarkus/domino/ProjectDependencyResolver.java
This change allows configuring custom local Maven repositories and user settings for dependency analysis with Domino
> Allow configuring local Maven repository and user settings in ProjectDependencyResolver
